### ISSUE TITLE
FACEBOOK TOKEN will be expired

### ISSUE THREAD

**Issue by polepoe** [RedditVN/redditvn-api#1]
Khi build back end cần FACEBOOK TOKEN, hiện tại có cách nào không cần dùng tới nó mà chỉ cần dùng FACEBOOK TOKEN của chính người dùng (cho login qua bằng app trên facebook để GET TOKEN) không.
Hoặc có thể dùng TOKEN nào mà không bao giờ expired?

**Comment by sontrinh** [comment]
Tạo 1 user mới cho vào group
Vào profile user đó, Ctrl+U, Ctrl+F tìm 'access_token'
Không đăng nhập user đấy ra khỏi trình duyệt thì 'access_token' sẽ never expire

_Khuyến cáo đây là access_token toàn quyền, nên rất nguy hiểm.
Khuyên lập nick mới chỉ phục vụ cho crawl post từ redditvn group_
